apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-imagepull
  namespace: demo-incidents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-imagepull
  template:
    metadata:
      labels:
        app: demo-imagepull
        version: v2
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
