apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - backend-servicemonitor.yaml
  - backend-hpa.yaml
  - postgres-pvc.yaml